#!/bin/sh
# ==============================================================================
# Conductor: A docker task runner
# ==============================================================================
# Author: Brad Jones <brad@bjc.id.au>
# Version: 0.0.1

# Grab the current directory, docker will complain if you use a relative path
self=$(readlink -f $0)
dir=`dirname ${self}`

# Build the conductor container
# TODO: This should really be a docker pull command I guess.
# But maybe we want diffrent build enviroments per project.
# The conductor image would expect the project src mounted so it could just use a RoboFile.
docker build -t brad-jones/conductor:latest $dir

# Run the freshly built image
# Run interactively with a tty
# Clean up the container after the task has complete
# Mount the hosts docker socket
# Mount the projects source into the container
# Proxy any arguments passed to this script through to the container.
socket="/var/run/docker.sock"
docker run -it --rm -v $socket:$socket -v $dir:/src brad-jones/conductor "$@"
