#!/usr/bin/env php
<?php

// Install Composer
require('/opt/brads-robo/vendor/autoload.php');

// Change into the main working dir
chdir('/mnt/src');

// Include the RoboFile
require('RoboFile.php');

// Initialise the runner
$runner = new \Brads\Robo\Runner();
$runner->execute('RoboFile');
